### ISSUE TITLE
W-16216516 Incorrect ClusterRole name in RoleBinding instructions for Authorized Namespaces in Openshift 

### ISSUE THREAD

**Issue by Paulo-Branco** [mulesoft/docs-runtime-fabric#1201]
The Authorized Namespaces setup guide for openshift installations mentions the `rtf:agent` role which does not exist in an authorized namespaces installation. Rather it should mention ` rtf:agent-<rtf_namespace>`

https://github.com/mulesoft/docs-runtime-fabric/blob/d960035172b46c482de7af9b414e68775d0bb41c/modules/ROOT/pages/install-multiple-instances-openshift.adoc?plain=1#L89C1-L89C1

The same step is correct in the setup guide for multiple RTF instances in the same cluster: 
https://github.com/mulesoft/docs-runtime-fabric/blob/v2.5/modules/ROOT/pages/install-multiple-instances.adoc?plain=1#L223

**Comment by kevintroller** [comment]
Created [W-16216516]for tracking.

**Comment by kevintroller** [comment]
Docs updated.
