### ISSUE TITLE
W-16216453 What version of openshift is this operator compatible with?

### ISSUE THREAD

**Issue by deanpeterson** [mulesoft/docs-runtime-fabric#1275]
The documentation doesn't say anywhere what versions of openshift the rtf operator is compatible with. I see red hats catalog says 4.6-4.10 but those versions of openshift are very old and out of support.

**Comment by kevintroller** [comment]
Created [W-16216453] for tracking.

**Comment by kevintroller** [comment]
Runtime Fabric only ties to the Kubernetes (K8s) version. Therefore, we don't track every cloud vendor's specific version in the public documentation. 
All these vendor versions, such as OpenShift, Rancher, and vSphere, have their own versioning, but they are all tied to a specific Kubernetes version.
