### ISSUE TITLE
[Enhancement Req] Include leveraging AMC Application Manager API as a deployment option

### ISSUE THREAD

**Issue by iponisio** [mulesoft/docs-runtime-fabric#243]
For some customers not willing to use the mule-maven-plugin as a deployment mechanism, It would be useful to include a section describing how to deploy an application to RTF just by leveraging the Exchange API, the Exchange Maven Facade API and the AMC Application Manager API. Thanks

**Comment by paigehargrave** [comment]
Created work item https://www.mulesoft.org/jira/browse/DOCS-8316.

**Comment by paigehargrave** [comment]
Closing this since https://www.mulesoft.org/jira/browse/DOCS-8316 is now closed.
