### ISSUE TITLE
Add 4.3 runtime to the docs

### ISSUE THREAD

**Issue by fcatae** [mulesoft/docs-runtime-fabric#288]
The deployment documentation does not include 4.3 runtime as supported.
https://github.com/mulesoft/docs-runtime-fabric/blob/v1.7/modules/ROOT/pages/deploy-index.adoc

However, RTF allows to use this latest version.

**Comment by paigehargrave** [comment]
Thank you @fcatae - please review https://github.com/mulesoft/docs-runtime-fabric/pull/289.

**Comment by paigehargrave** [comment]
Closing this issue b/c https://github.com/mulesoft/docs-runtime-fabric/pull/289 is now merged.
