### ISSUE TITLE
Rm command  in RTF uninstall steps uses hyphen instead of underscore

### ISSUE THREAD

**Issue by bdjtcg** [mulesoft/docs-runtime-fabric#353]
https://docs.mulesoft.com/runtime-fabric/1.7/uninstall-manual
In step 5, after running command:
`rm /etc/systemd/system/install-teleport-*.service /etc/systemd/system/install-planet-*.service /etc/systemd/system/shrink-*.service /etc/systemd/system/gravity__gravitational.io__teleport__*.service /etc/systemd/system/gravity__gravitational.io__planet-*.service`

There were remaining files of type: gravity__gravitational.io__planet_*.service

I believe the hyphen needs to updated to underscore to fully remove these files:
`/etc/systemd/system/gravity__gravitational.io__planet-*.service" -->
"/etc/systemd/system/gravity__gravitational.io__planet_*.service`

**Comment by IsaacEldridge** [comment]
@sarjeet2013 Can you confirm that this is correct? We won't update this older version, but I will make this change on 1.9 onwards if it applies.

**Comment by sarjeet2013** [comment]
@kmendiratta-crm Can you review this?

**Comment by kevintroller** [comment]
@bdjtcg We are closing this contribution because it has exceeded the age limit for a timely merge. If the contribution is still valid, please open a separate GitHub issue or pull request.
