### ISSUE TITLE
Enable TLSv1 in RTF runtime fabric

### ISSUE THREAD

**Issue by manojmck** [mulesoft/docs-runtime-fabric#423]
Hi Team,

We are using legacy MDM which accepts TLsv1 and we are getting below error. How can we fix this issue? Where can I find tls-default.conf in RTF?

 failed: Server chose TLSv1, but that protocol version is not enabled or not supported by the client..",

**Comment by IsaacEldridge** [comment]
Sorry for the late response, but if you haven't resolved this issue, please contact MuleSoft support. Thanks. https://help.mulesoft.com/s/support
