### ISSUE TITLE
Anypoint Platform Roles and Permissions section is duplicated

### ISSUE THREAD

**Issue by yyamano** [mulesoft/docs-runtime-fabric#807]
"Anypoint Platform Roles and Permissions" section is duplicated at https://github.com/mulesoft/docs-runtime-fabric/blob/v1.13/modules/ROOT/pages/index-self-managed.adoc

* https://github.com/mulesoft/docs-runtime-fabric/blob/v1.13/modules/ROOT/pages/index-self-managed.adoc#anypoint-platform-roles-and-permissions
* https://github.com/mulesoft/docs-runtime-fabric/blob/v1.13/modules/ROOT/pages/index-self-managed.adoc#anypoint-platform-roles-and-permissions-1

**Comment by kevintroller** [comment]
Hi @yyamano  Thank you for your contribution. We have moved the changes to a new pull request
https://github.com/mulesoft/docs-runtime-fabric/pull/1050
